# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 635e2b32b14d8812c7f13fc985b1ff51c18cf7b81605ffead5206d6cd2a38565d29d63084de4e4576d092d8bde7de3ab067c2e63c6fbe1530b17119361911862

test:
  secret_key_base: ea7994510903923d9e9f31f7255479620d9aa3c1ab6617cace28d3b81335e104703addd762efd6b77fffb17cedc1459f8961070a5daf6ed235e9c0c50126e817

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
